### ISSUE TITLE
Create External Stylesheet for Production

### ISSUE THREAD

**Issue by simensta** [zooniverse/zoo-react-starterify#34]
Let's use [extract text plugin for webpack] (https://github.com/webpack/extract-text-webpack-plugin) to create a separate css bundle file for production.

@srallen, @amyrebecca: feel free to add anything else from our earlier conversation!

**Comment by srallen** [comment]
@simensta I just happened to submit a PR that adds it in! Check out #33

**Comment by srallen** [comment]
Just to clarify, the extract text plugin was already loaded up, but wasn't working, so I fixed it.

**Comment by simensta** [comment]
@srallen: excellent!
